//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new song.
        /// </summary>
        public static string AddSong {
            get {
                return ResourceManager.GetString("AddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic CRUD.
        /// </summary>
        public static string BasicCRUD {
            get {
                return ResourceManager.GetString("BasicCRUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord.
        /// </summary>
        public static string Chord {
            get {
                return ResourceManager.GetString("Chord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChordNote.
        /// </summary>
        public static string ChordNote {
            get {
                return ResourceManager.GetString("ChordNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument.
        /// </summary>
        public static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen on Spotify.
        /// </summary>
        public static string ListenOnSpotify {
            get {
                return ResourceManager.GetString("ListenOnSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord notes.
        /// </summary>
        public static string NavChordNotes {
            get {
                return ResourceManager.GetString("NavChordNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chords.
        /// </summary>
        public static string NavChords {
            get {
                return ResourceManager.GetString("NavChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string NavFolders {
            get {
                return ResourceManager.GetString("NavFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments.
        /// </summary>
        public static string NavInstruments {
            get {
                return ResourceManager.GetString("NavInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NavNotes {
            get {
                return ResourceManager.GetString("NavNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song chords.
        /// </summary>
        public static string NavSongChords {
            get {
                return ResourceManager.GetString("NavSongChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song instruments.
        /// </summary>
        public static string NavSongInstruments {
            get {
                return ResourceManager.GetString("NavSongInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song keys.
        /// </summary>
        public static string NavSongKeys {
            get {
                return ResourceManager.GetString("NavSongKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string NavSongs {
            get {
                return ResourceManager.GetString("NavSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string NavStyles {
            get {
                return ResourceManager.GetString("NavStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabs.
        /// </summary>
        public static string NavTabs {
            get {
                return ResourceManager.GetString("NavTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string NavVideos {
            get {
                return ResourceManager.GetString("NavVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search result.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search songs.
        /// </summary>
        public static string SearchSongs {
            get {
                return ResourceManager.GetString("SearchSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongChord.
        /// </summary>
        public static string SongChord {
            get {
                return ResourceManager.GetString("SongChord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongInFolder.
        /// </summary>
        public static string SongInFolder {
            get {
                return ResourceManager.GetString("SongInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongInstrument.
        /// </summary>
        public static string SongInstrument {
            get {
                return ResourceManager.GetString("SongInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongKey.
        /// </summary>
        public static string SongKey {
            get {
                return ResourceManager.GetString("SongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongStyle.
        /// </summary>
        public static string SongStyle {
            get {
                return ResourceManager.GetString("SongStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TuningNote.
        /// </summary>
        public static string TuningNote {
            get {
                return ResourceManager.GetString("TuningNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all songs.
        /// </summary>
        public static string ViewAllSongs {
            get {
                return ResourceManager.GetString("ViewAllSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
